### ISSUE TITLE
node-red crashed when api.corrently.io is down

### ISSUE THREAD

**Issue by dickesW** [energychain/node-red-contrib-discovergy-meter#113]
Hi @zoernert 

today my node-red crashed right after a fresh start with the error:

26 Jul 23:42:38 - [red] Uncaught Exception:
26 Jul 23:42:38 - [error] Error: connect ETIMEDOUT 85.25.133.34:443

I was able to trace the crash to the call of the Discovergy Meter Node which is called 2 seconds after the start of node-red via an inject node and is called every 30 seconds. As this just happens when api.corrently.io was/is down I guess it is related. My Discovergy Meter is connected to my corrently account. 

The crash only happens with the automated trigger after the reboot. When I disable the the automated inject node and trigger the node manually I will also not get an output but node-red is not crashing.

![grafik](https://user-images.githubusercontent.com/42518853/181117881-82600b8f-7322-47ca-952f-efe66eede953.png)

Thanks for your help
dickesW

**Comment by zoernert** [comment]
> 26 Jul 23:42:38 - [error] Error: connect ETIMEDOUT 85.25.133.34:443

This got caused by an exceeded rate limit in case your flows starts fresh. The current API rate limit is now handled much more strict on the Discovergy side.... however you are right it would be nice to catpure the exception correctly. 

BTW the corrently API has an external monitored uptime of 100% within the last 30 days :)

I will put this issue to an enhancement request for the exception handling as I personaly expect more issues with the connection to Discovergy Backend on the horizion.

**Comment by zoernert** [comment]
Marketdata Pricing got removed for the moment as feature (see commit cfcf4a6140371baa6d0509eca3b40ddac8ce4b11 ) this needs to be ported to new Marketdata API. 

Version 0.7.1 should fix this issue.

**Comment by zoernert** [comment]
To clearify: The successor project "casa-corrently" (  https://github.com/energychain/casa-corrently ) was not affected as it  allows other meters than Discovergy and is based on a different implementation.
